repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: check-json
      - id: pretty-format-json
        args:
          - --no-sort-keys
          - --autofix
      - id: check-merge-conflict
        args:
          - --assume-in-merge
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      #
      # Go Mod Tidy
      #
      - id: go-mod-tidy
      - id: go-mod-tidy-repo
      #
      # Go Test
      #
      - id: go-test-mod
      # - id: go-test-pkg
      - id: go-test-repo-mod
      # - id: go-test-repo-pkg
      #
      # Formatters
      #
      - id: go-fmt
      - id: go-fmt-repo
      #
      # Style Checkers
      #
      # - id: golangci-lint
      - id: golangci-lint-mod
      # - id: golangci-lint-pkg
      # - id: golangci-lint-repo-mod
      # - id: golangci-lint-repo-pkg
