name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x' # Use the Go version specified in go.mod

    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o csql-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} ./cmd/csql.go
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: csql-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
        path: csql-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

    - name: Upload to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: csql-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
        asset_name: csql-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
